CC := gcc
CFLAGS := -std=c11 -Wall -Wextra -Wpedantic
CPPFLAGS :=

ifeq ($(OS),Windows_NT)
TARGET := main.exe
TEST_TARGET := tests/test_punto.exe
RUN := .\$(TARGET)
RUN_TEST := .\tests\test_punto.exe
RM := del /Q
else
TARGET := main
TEST_TARGET := tests/test_punto
RUN := ./$(TARGET)
RUN_TEST := ./$(TEST_TARGET)
RM := rm -f
endif

OBJ := main.o Punto/punto.o Archivio/archivio.o
LIB_OBJ := Punto/punto.o Archivio/archivio.o
TEST_OBJ := tests/test_punto.o

.PHONY: all run test clean rebuild

all: $(TARGET)

$(TARGET): $(OBJ)
	$(CC) $(OBJ) -o $@

main.o: main.c Punto/punto.h Archivio/archivio.h
	$(CC) $(CPPFLAGS) $(CFLAGS) -c $< -o $@

Punto/punto.o: Punto/punto.c Punto/punto.h
	$(CC) $(CPPFLAGS) $(CFLAGS) -c $< -o $@

Archivio/archivio.o: Archivio/archivio.c Archivio/archivio.h Punto/punto.h
	$(CC) $(CPPFLAGS) $(CFLAGS) -c $< -o $@

tests/test_punto.o: tests/test_punto.c Punto/punto.h Archivio/archivio.h
	$(CC) $(CPPFLAGS) $(CFLAGS) -c $< -o $@

$(TEST_TARGET): $(TEST_OBJ) $(LIB_OBJ)
	$(CC) $(TEST_OBJ) $(LIB_OBJ) -o $@

run: $(TARGET)
	$(RUN)

test: $(TEST_TARGET)
	$(RUN_TEST)

clean:
ifeq ($(OS),Windows_NT)
	-$(RM) main.o Punto\punto.o Archivio\archivio.o tests\test_punto.o $(TARGET) tests\test_punto.exe 2>NUL
else
	$(RM) main.o Punto/punto.o Archivio/archivio.o tests/test_punto.o $(TARGET) $(TEST_TARGET)
endif

rebuild: clean all
