CC := gcc
CFLAGS := -std=c11 -Wall -Wextra
TARGET := main.exe

SRC := main.c \
       Punto/punto.c \
       Archivio/archivio.c

OBJ := main.o \
       Punto/punto.o \
       Archivio/archivio.o

.PHONY: all run clean rebuild

all: $(TARGET)

$(TARGET): $(OBJ)
	$(CC) $(OBJ) -o $(TARGET)

main.o: main.c Punto/punto.c Punto/punto.h Archivio/archivio.c Archivio/archivio.o 
	$(CC) $(CFLAGS) -c main.c -o main.o

Punto/punto.o : Punto/punto.h
	$(CC) $(CFLAGS) -c Punto/punto.c -o Punto/punto.o 
	
Archivio/archivio.o : Archivio/archivio.c Archivio/archivio.h
	$(CC) $(CFLAGS) -c Archivio/archivio.c -o Archivio/archivio.o 

run: $(TARGET)
	.\$(TARGET)

clean:
	@if exist main.o del /Q main.o
	@if exist Archivio/archivio.o del /Q Archivio/archivio.o 
	@if exist Punto/punto.o del /Q Punto/punto.o
	@if exist $(TARGET) del /Q $(TARGET)

rebuild: clean all
